### ISSUE TITLE
[데이터 시각화] 판매 현황 데이터 차트

### ISSUE THREAD

**Issue by heegu0311** [heegu0311/Partof#28]
### ISSUE

- Group: `client`
- Type:
1. [x] `feature`

### TODO

1. [x] 관리자 페이지 라우트 추가
2. [x] sales 데이터 요청 API 로직(oAuth) 추가
3. [x] 차트 2종 추가(Doughnut / Line Chart)
